### ISSUE TITLE
Assigning Functions to Variables section could use more

### ISSUE THREAD

**Issue by alexgriff** [learn-co-curriculum/js-advanced-functions-first-class-functions-readme#1]
*Assigning Functions to Variables* goes straight from this:
```js
const myFunc = function () {
  return 6 + 9;
};
```
to this:
```js
myFunc();
// => 15
```

If I was explaining this to a student, I would dwell longer here.
something like: 
Now if we wrote, 
```js
myFunc
```
should we expect to see `15` ??
No, we'll see the *definiton of the function itself*.
Our variables stores a reference to the function itself. We can call it whenever we want to/

Since typing `myFunc` returns a function, we can invoke that function like we invoke any other function with `()`

we can see 15 by typing
```js
myFunc()
// => 15

myFunc() + 1
// => 16

myFunc + 1
// => "function (){...}1"
```

**Comment by drakeltheryuujin** [comment]
Hi @alexgriff,

Thank you for your feedback. We've updated the materials to address this issue.

Thanks for contributing! 💙
