### ISSUE TITLE
I think there's a mistake in an example code snippet.

### ISSUE THREAD

**Issue by Rexman17** [learn-co-curriculum/js-advanced-functions-first-class-functions-readme#2]
```javascript
(function (name, year, claimToFame) {
  console.log(`Hi, I'm ${name}, I was born in ${year}, and I ${claimToFame}!`);
})('Ada Lovelace', 1815, 'was the first computer programmer');
// LOG: Hi, I'm Ada Lovelace, and I was the first computer programmer!
 
(function (name, year, claimToFame) {
  console.log(`Hi, I'm ${name}, I was born in ${year}, and I ${claimToFame}!`);
})('Grace Hopper', 1906, 'invented one of the first compilers');
// LOG: Hi, I'm Grace Hopper, and I invented one of the first compilers!
```

The logs are incorrect. if you paste the code into the dev tools, you will see:
Hi, I'm Ada Lovelace, I was born in 1815, and I was the first computer programmer!

and 

Hi, I'm Grace Hopper, I was born in 1906, and I invented one of the first compilers!

The examples in the reading are missing the "I was born" part.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @Rexman17.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
