### ISSUE TITLE
Consider breaking this lesson into smaller bits

### ISSUE THREAD

**Issue by artismarti** [learn-co-curriculum/js-advanced-functions-first-class-functions-readme#3]
This is so long drawn, it's hard to stay focused on the large wall of text.

Thank you

**Comment by maxwellbenton** [comment]
Hi @artismarti,

Thank you for providing this feedback. We've labeled this lesson as having known issues in need of rework and referenced your issue in #4. We're in the process of developing new JavaScript materials and will update this content in the near future.

Thank you again for bringing this to our attention.
